language: node_js
node_js:
  - '9'
cache:
  directories:
    - "~/.npm"
    - node_modules
install:
  - npm install -g codecov
  - npm install
script:
  - npm test
  - codecov
before_deploy:
  - npm run build
  - zip -r fonticonpicker.react.zip dist/*
deploy:
  - provider: npm
    email: swashata4u@gmail.com
    api_key:
      secure: "bHgvGq9JqIEZ8ETc1JzpxUUQ1X6DYmAvPDUJ7qsa+l4QzrbZd4lXDgPRhd8rs7iHp2aLADK3QcObDGXEyH5/4hlGHRQUVewnSMJaGkl2o9JGf0lPwSWKnzfyr58p6e7r4IQhKyxT/4bVnlmdCCEseCtxRAIF1kcXnf8H4rnx79vPPTntgDwQ3M/ABI9CBQeU0/53idN0Dc67Sc7cbXqym4d+twnZe+sdRHpdyYWDvD+fWr7rvxp9VcHbdwS/W7Id0wKPImAX4XoG2RoMfzi/jH1Trlc8s6k2JhrKVAcGKknCZAm+QEM20GuYeCk4PjPzfxESYzS1dKpDIjCdvV5fOgNWIpublZTfAQQqFFgUNgWx5ilqOseDiLPoQX8WL/sJU0ZEikdT5nof1J15RwAYB7A/GlKSJmanI04DYZOb4d4oCtfYBYnHaT9r1AiaQQbWZqfOz87ZnphHbbPVf99psRcHxNsA8KyuY0FrTBiNpr05IDCZuoEmQX0lriN8dAtolka56pdZX5C0j+n574/dAK5j2VUMWSC325vu1s+c+2JKvxF3X1DIHpzvfZfa6IW+2RdKgqUmMnyln/jIEPIfj02xpFQix95YJpgNDyI8LP3GRRAMvWzC7h6MstiqVPft3snL8N3r//2/Yvtr82Eprl8NxBxka6L39OAv2dykVE8="
    on:
      tags: true
      repo: fontIconPicker/react-fonticonpicker
    skip_cleanup: true
    overwrite: true
  - provider: releases
    api_key:
      secure: "L+pvvSqw7GW+pB5mzWRSYZ4GhHumFGtv2ZSu4SSysCmXIJTExccTgNXtrKpUjXaHC7GJGl0gpAq3Z1IE0LTFAgkRlHLq4OvY+UoTiOlof8dGr3BXEyc/hHOVo76pdxH1O4vycpc8Psin7FOINXj5TsV4DwyS/Q7yGS3PQoDasPY2491plZLTSujf18m+Bz984KT6PzHDo8j/tngcj+ZQhkmU1BJyvgoCF10i9vI3G0zQ14APlKFVJwPig4bzjYJ5u8kEqLjHgByZz+xvW98+0JJq+7hzqr9yj8FU4ZA/AruWYO9aCplIXmA9mfTcS+WNhkfIhAojNAt225+yBqv7qQbwfK5RRjGhQh+KvEJ2AtMdlhk4G/mhS433vudXbgU5lTyfT3BGia7V7GGuujYoZNBmqtJ+G6hYLHvsUh61QVjjKe/2drCY6XSSshFYwu/+fssXX00oSUnWWys7WfK7FHBLEDtHikz1T1IMDigTHoFTJXJBmHUNJCriC48UQP0VWZ9I+MTZIofHafhn+DvbHVzpK/6trMsEyiSRJQH3ZZYlQosNdObNz470LssFD9u2PBKPhH+T2Q4gZSDYbyDLUZKsf8K4NyAkt6hBX8hhxXTNw2MyLDAIbT5ns3dN+XEhEu3dqWb0Cd3h03ucJgCwXss0P4kMehAjokEXwzvEWik="
    file:
      - fonticonpicker.react.zip
    on:
      tags: true
      repo: fontIconPicker/react-fonticonpicker
    skip_cleanup: true
    overwrite: true
